-- seed part 01 · settings (6) + template_categories (15) — run first, in order
insert into public.settings (key, value)
values
  ('brand', '{"logo_url": "/branify-logo-horizontal.svg", "favicon_url": "/branify-icon.svg", "default_og_image": "/og/home.jpg"}'::jsonb),
  ('contact', '{"email": "admin@branify.store", "phone": "+8801879176373", "offices": [{"label": "USA Office", "lines": ["Remote-first", "Serving worldwide"]}, {"label": "Bangladesh Office", "lines": ["Dhaka", "Bangladesh"]}], "whatsapp": "923321029333", "whatsapp_display": "+92 332 1029333"}'::jsonb),
  ('general', '{"tagline": "Luxury Digital Studio & Futuristic Technology", "site_url": "https://branify-new.vercel.app", "site_name": "BRANIFY"}'::jsonb),
  ('performance', '{"analytics_provider": "first_party"}'::jsonb),
  ('seo_defaults', '{"default_title": "BRANIFY — Luxury Digital Studio & Futuristic Technology", "title_template": "%s | BRANIFY", "default_og_image": "/og/home.jpg", "title_max_length": 60, "default_description": "BRANIFY is a futuristic digital studio delivering web development, branding, AI solutions, 100+ free tools and premium digital products for ambitious international brands.", "description_max_length": 160}'::jsonb),
  ('social', '{"tiktok": "https://www.tiktok.com/@branify", "youtube": "https://www.youtube.com/@branify", "facebook": "https://facebook.com/branify", "linkedin": "https://www.linkedin.com/company/branify", "instagram": "https://instagram.com/branify"}'::jsonb)
on conflict (key) do update set value = excluded.value;

insert into public.template_categories (name, slug, tagline, hero_description, image, seo_title, seo_description, og_image, active, sort_order)
values
  ('Restaurant & Food', 'restaurant-food', 'Fine dining, bistros and street food brands.', 'Explore responsive restaurant website templates designed for modern dining businesses, cafés, food brands and hospitality companies — with menu presentation, reservations and gallery sections built in.', '', 'Restaurant & Food Website Templates — BRANIFY', 'Explore responsive restaurant website templates designed for modern dining businesses, cafés, food brands and hospitality companies — with menu presentation, reservations and gallery sections built in.', '', true, 0),
  ('Real Estate', 'real-estate', 'Property listings and luxury real estate.', 'Explore real estate website templates designed for agencies, brokerages and luxury property brands — with listing showcases, neighborhood highlights and enquiry-first lead capture.', '', 'Real Estate Website Templates — BRANIFY', 'Explore real estate website templates designed for agencies, brokerages and luxury property brands — with listing showcases, neighborhood highlights and enquiry-first lead capture.', '', true, 1),
  ('Fashion & Accessories', 'fashion-accessories', 'Editorial fashion, e-commerce and jewelry.', 'Explore fashion website templates designed for labels, boutiques and accessory brands — with lookbook grids, collection storytelling and conversion-ready product layouts.', '', 'Fashion & Accessories Website Templates — BRANIFY', 'Explore fashion website templates designed for labels, boutiques and accessory brands — with lookbook grids, collection storytelling and conversion-ready product layouts.', '', true, 2),
  ('Beauty & Salon', 'beauty-salon', 'Salons, spas and beauty studios.', 'Explore beauty and salon website templates designed for salons, spas and beauty studios — with service menus, stylist profiles and booking call-to-actions built in.', '', 'Beauty & Salon Website Templates — BRANIFY', 'Explore beauty and salon website templates designed for salons, spas and beauty studios — with service menus, stylist profiles and booking call-to-actions built in.', '', true, 3),
  ('Healthcare & Medical', 'healthcare-medical', 'Clinics, medical centers and wellness practices.', 'Explore healthcare website templates designed for clinics, medical centers and wellness practices — with department pages, doctor directories and appointment funnels.', '', 'Healthcare & Medical Website Templates — BRANIFY', 'Explore healthcare website templates designed for clinics, medical centers and wellness practices — with department pages, doctor directories and appointment funnels.', '', true, 4),
  ('Interior Design', 'interior-design', 'Studios and architects presenting spaces.', 'Explore interior design and architecture website templates designed for studios and practices — with project spotlights, material galleries and consultation enquiries.', '', 'Interior Design Website Templates — BRANIFY', 'Explore interior design and architecture website templates designed for studios and practices — with project spotlights, material galleries and consultation enquiries.', '', true, 5),
  ('Fitness & Lifestyle', 'fitness-lifestyle', 'Gyms, yoga studios and wellness brands.', 'Explore fitness and lifestyle website templates designed for gyms, studios, coaches and wellness brands — with class schedules, trainer profiles and membership tiers.', '', 'Fitness & Lifestyle Website Templates — BRANIFY', 'Explore fitness and lifestyle website templates designed for gyms, studios, coaches and wellness brands — with class schedules, trainer profiles and membership tiers.', '', true, 6),
  ('Tech & Digital', 'tech-digital', 'SaaS platforms, apps and digital agencies.', 'Explore tech and SaaS website templates designed for software platforms, apps and digital agencies — with feature walkthroughs, integration grids and pricing sections.', '', 'Tech & Digital Website Templates — BRANIFY', 'Explore tech and SaaS website templates designed for software platforms, apps and digital agencies — with feature walkthroughs, integration grids and pricing sections.', '', true, 7),
  ('Automotive', 'automotive', 'Dealerships, detailing and workshops.', 'Explore automotive website templates designed for dealerships, detailing studios and workshops — with inventory showcases, service menus and test-drive funnels.', '', 'Automotive Website Templates — BRANIFY', 'Explore automotive website templates designed for dealerships, detailing studios and workshops — with inventory showcases, service menus and test-drive funnels.', '', true, 8),
  ('Home Services', 'home-services', 'Cleaning, trade and relocation services.', 'Explore home services website templates designed for cleaning, trade and relocation companies — with quote-first funnels, service checklists and trust signals.', '', 'Home Services Website Templates — BRANIFY', 'Explore home services website templates designed for cleaning, trade and relocation companies — with quote-first funnels, service checklists and trust signals.', '', true, 9),
  ('Education', 'education', 'Schools, tutoring and course platforms.', 'Explore education website templates designed for schools, tutors and course platforms — with subject grids, program pages and enrollment funnels.', '', 'Education Website Templates — BRANIFY', 'Explore education website templates designed for schools, tutors and course platforms — with subject grids, program pages and enrollment funnels.', '', true, 10),
  ('Business & Professional Services', 'business-services', 'Consultancies, law firms and B2B practices.', 'Explore professional services website templates designed for consultancies, law firms and B2B practices — with authority-led design, case studies and enquiry flows.', '', 'Business & Professional Services Website Templates — BRANIFY', 'Explore professional services website templates designed for consultancies, law firms and B2B practices — with authority-led design, case studies and enquiry flows.', '', true, 11),
  ('Pet Care', 'pet-care', 'Groomers, spas and veterinary clinics.', 'Explore pet care website templates designed for groomers, spas and veterinary clinics — with service menus, team introductions and friendly booking flows.', '', 'Pet Care Website Templates — BRANIFY', 'Explore pet care website templates designed for groomers, spas and veterinary clinics — with service menus, team introductions and friendly booking flows.', '', true, 12),
  ('Events & Creative', 'events-creative', 'Weddings, event production and photography.', 'Explore events and creative website templates designed for wedding planners, event producers, photographers and studios — with portfolio galleries and enquiry journeys.', '', 'Events & Creative Website Templates — BRANIFY', 'Explore events and creative website templates designed for wedding planners, event producers, photographers and studios — with portfolio galleries and enquiry journeys.', '', true, 13),
  ('Catering Services', 'catering-services', 'Caterers and private chefs.', 'Explore catering website templates designed for caterers and private chefs — with menus, package tiers and enquiry flows that turn visitors into bookings.', '', 'Catering Services Website Templates — BRANIFY', 'Explore catering website templates designed for caterers and private chefs — with menus, package tiers and enquiry flows that turn visitors into bookings.', '', true, 14)
on conflict (slug) do update set name = excluded.name, tagline = excluded.tagline, hero_description = excluded.hero_description, image = excluded.image, seo_title = excluded.seo_title, seo_description = excluded.seo_description, og_image = excluded.og_image, active = excluded.active, sort_order = excluded.sort_order;
