-- seed part 08 · tools (136) — rows 1-25 of 136
insert into public.tools (slug, name, category, description, icon, url, input_type, active, featured, popular, sort_order, seo, archived)
values
  ('pdf-to-text', 'PDF Text Extractor', 'PDF Tools', 'Extract raw text content from PDF files directly in your browser without uploading to external servers.', 'FileText', '/tools/pdf-to-text', 'file', true, true, true, 0, '{"title": "Free PDF Text Extractor Tool — BRANIFY", "keywords": ["pdf to text", "extract pdf text", "pdf reader", "pdf converter"], "description": "Extract text from any PDF document online instantly in your browser."}'::jsonb, false),
  ('pdf-word-counter', 'PDF Word Counter', 'PDF Tools', 'Count words, characters, pages, and estimated reading time from any PDF document.', 'Hash', '/tools/pdf-word-counter', 'file', true, false, false, 1, '{"title": "PDF Word Counter — BRANIFY Tools", "keywords": ["pdf word count", "count words in pdf", "pdf reader"], "description": "Instantly count total words, characters, and pages in a PDF file."}'::jsonb, false),
  ('pdf-metadata-viewer', 'PDF Metadata Viewer', 'PDF Tools', 'View hidden metadata, author information, creation dates, PDF producer, and version info.', 'Info', '/tools/pdf-metadata-viewer', 'file', true, false, false, 2, '{"title": "PDF Metadata & Properties Inspector", "keywords": ["pdf metadata", "inspect pdf", "pdf properties"], "description": "Inspect PDF metadata including author, title, keywords, and creation dates."}'::jsonb, false),
  ('pdf-page-counter', 'PDF Page Inspector & Splitter Helper', 'PDF Tools', 'Inspect page layouts, dimensions, aspect ratios, and total page count for PDF documents.', 'Layers', '/tools/pdf-page-counter', 'file', true, false, false, 3, '{"title": "PDF Page Structure & Inspector Tool", "keywords": ["pdf pages", "pdf inspector", "pdf layout"], "description": "Analyze PDF page dimensions, page count, and structural metadata."}'::jsonb, false),
  ('pdf-text-cleaner', 'PDF Copy Text Formatter', 'PDF Tools', 'Paste messy text copied from PDFs to strip out unwanted line breaks, hyphens, and weird spacing.', 'Sparkles', '/tools/pdf-text-cleaner', 'textarea', true, false, false, 4, '{"title": "Fix Messy PDF Copied Text — Clean Line Breaks", "keywords": ["fix pdf text", "clean pdf copy", "remove line breaks pdf"], "description": "Clean up ugly line breaks and formatting glitches when copying text from PDF files."}'::jsonb, false),
  ('pdf-merge-planner', 'PDF Merge & Combine Guide', 'PDF Tools', 'Organize files and inspect multiple PDF documents before merging or printing.', 'Combine', '/tools/pdf-merge-planner', 'file', true, false, false, 5, '{"title": "PDF File Inspector & Merge Prep", "keywords": ["pdf merge", "combine pdf", "pdf files"], "description": "Inspect and prepare multiple PDF files for document assembly."}'::jsonb, false),
  ('pdf-page-number-gen', 'PDF Page Numbering Labeler', 'PDF Tools', 'Generate customizable page number headers and footers for PDF documents.', 'FileDigit', '/tools/pdf-page-number-gen', 'form', true, false, false, 6, '{"title": "PDF Page Number Format Generator", "keywords": ["pdf page numbers", "pdf numbering", "footer labels"], "description": "Create custom header/footer numbering labels for reports and ebooks."}'::jsonb, false),
  ('pdf-size-estimator', 'PDF Compression & Size Estimator', 'PDF Tools', 'Calculate potential file size savings and target compression ratios before emailing PDFs.', 'Minimize2', '/tools/pdf-size-estimator', 'file', true, false, false, 7, '{"title": "PDF Size & Compression Estimator", "keywords": ["compress pdf size", "pdf optimizer", "reduce pdf size"], "description": "Estimate compressed PDF size and optimization metrics."}'::jsonb, false),
  ('pdf-unlock-checker', 'PDF Security & Encryption Inspector', 'PDF Tools', 'Check if a PDF file is password protected, encrypted, or has printing/copy restrictions.', 'Lock', '/tools/pdf-unlock-checker', 'file', true, false, false, 8, '{"title": "PDF Security & Password Status Checker", "keywords": ["check pdf password", "pdf security status", "pdf restrictions"], "description": "Inspect PDF document permissions and security locks."}'::jsonb, false),
  ('pdf-watermark-generator', 'PDF Watermark Text Stamp Creator', 'PDF Tools', 'Create draft, confidential, or custom watermark text rules for overlaying on documents.', 'Stamp', '/tools/pdf-watermark-generator', 'form', true, false, false, 9, '{"title": "PDF Watermark Generator Online", "keywords": ["pdf watermark", "watermark stamp", "confidential watermark"], "description": "Generate custom text watermark stamp rules for confidential PDF files."}'::jsonb, false),
  ('pdf-to-base64', 'PDF to Base64 Encoder', 'PDF Tools', 'Convert PDF files into Base64 data URI strings for embedding in code or APIs.', 'Code', '/tools/pdf-to-base64', 'file', true, false, false, 10, '{"title": "PDF to Base64 Data URI Converter", "keywords": ["pdf to base64", "encode pdf", "base64 pdf URI"], "description": "Convert PDF documents into Base64 encoded data strings."}'::jsonb, false),
  ('base64-to-pdf', 'Base64 to PDF Decoder', 'PDF Tools', 'Paste Base64 data strings to convert back into downloadable PDF documents.', 'FileCheck', '/tools/base64-to-pdf', 'textarea', true, false, false, 11, '{"title": "Base64 to PDF File Decoder", "keywords": ["base64 to pdf", "decode base64 pdf", "convert base64"], "description": "Decode Base64 text string into downloadable PDF document."}'::jsonb, false),
  ('image-compressor', 'Image Compressor (PNG / JPG / WebP)', 'Image Tools', 'Compress PNG, JPG, and WebP images directly in your browser with adjustable quality levels.', 'Image', '/tools/image-compressor', 'image', true, true, true, 12, '{"title": "Free Online Image Compressor — PNG & JPG", "keywords": ["image compressor", "compress png", "compress jpg", "reduce image size"], "description": "Reduce image file size in your browser without quality loss."}'::jsonb, false),
  ('image-resizer', 'Pixel Image Resizer', 'Image Tools', 'Resize image width and height dimensions with aspect ratio lock.', 'Maximize2', '/tools/image-resizer', 'image', true, false, true, 13, '{"title": "Online Image Resizer — Custom Pixel Width & Height", "keywords": ["image resizer", "resize photo", "change image dimensions"], "description": "Resize photos and graphics to exact pixel dimensions instantly."}'::jsonb, false),
  ('image-converter-webp', 'JPG/PNG to WebP Converter', 'Image Tools', 'Convert heavy PNG or JPEG photos into fast-loading WebP format.', 'RefreshCw', '/tools/image-converter-webp', 'image', true, true, false, 14, '{"title": "Convert PNG/JPG to WebP Image Format", "keywords": ["convert to webp", "png to webp", "jpg to webp"], "description": "Convert images to high-compression WebP format for faster web speed."}'::jsonb, false),
  ('jpg-to-png', 'JPG to PNG Converter', 'Image Tools', 'Convert JPEG images into high-quality PNG format with lossless encoding.', 'FileImage', '/tools/jpg-to-png', 'image', true, false, false, 15, '{"title": "JPG to PNG Converter Online", "keywords": ["jpg to png", "convert jpeg to png", "image converter"], "description": "Convert JPG images to PNG format instantly."}'::jsonb, false),
  ('png-to-jpg', 'PNG to JPG Converter (Solid White Background)', 'Image Tools', 'Convert transparent or large PNG images to lightweight JPG graphics.', 'FileImage', '/tools/png-to-jpg', 'image', true, false, false, 16, '{"title": "PNG to JPG Converter Online", "keywords": ["png to jpg", "convert png to jpeg", "photo converter"], "description": "Convert PNG graphics to JPG format with solid background fill."}'::jsonb, false),
  ('color-picker-image', 'Image Color Palette Extractor', 'Image Tools', 'Upload an image to automatically extract dominant HEX, RGB, and color scheme codes.', 'Palette', '/tools/color-picker-image', 'image', true, false, false, 17, '{"title": "Image Color Palette & HEX Code Extractor", "keywords": ["image color picker", "color palette generator", "extract hex from image"], "description": "Extract dominant color scheme and HEX codes from any uploaded photo."}'::jsonb, false),
  ('image-to-base64', 'Image to Base64 String Encoder', 'Image Tools', 'Convert PNG, JPG, or SVG images into inline CSS/HTML Base64 Data URLs.', 'Code', '/tools/image-to-base64', 'image', true, false, false, 18, '{"title": "Image to Base64 Converter Online", "keywords": ["image to base64", "base64 image encoder", "data uri image"], "description": "Convert images into Base64 data strings for inline CSS/HTML."}'::jsonb, false),
  ('base64-to-image', 'Base64 to Image Decoder', 'Image Tools', 'Paste Base64 Data URLs to render and download as PNG/JPG graphics.', 'Download', '/tools/base64-to-image', 'textarea', true, false, false, 19, '{"title": "Base64 to Image Decoder & Previewer", "keywords": ["base64 to image", "decode base64 image", "base64 image viewer"], "description": "Decode Base64 strings back into viewable PNG or JPG images."}'::jsonb, false),
  ('favicon-generator', 'Favicon & App Icon Generator (16x16, 32x32, 64x64)', 'Image Tools', 'Convert logo graphics into square 16x16, 32x32, and 64x64 favicon PNG files.', 'Globe', '/tools/favicon-generator', 'image', true, true, false, 20, '{"title": "Favicon & Website Icon Generator", "keywords": ["favicon generator", "make favicon", "website icon creator"], "description": "Generate multi-resolution favicon graphics for web projects."}'::jsonb, false),
  ('image-blur-tool', 'Image Blur & Privacy Masking', 'Image Tools', 'Apply subtle gaussian blur filters to protect sensitive information or create backgrounds.', 'EyeOff', '/tools/image-blur-tool', 'image', true, false, false, 21, '{"title": "Image Blur & Background Masking Tool", "keywords": ["blur image", "photo blur tool", "privacy mask photo"], "description": "Apply privacy blur effects to photos and background graphics."}'::jsonb, false),
  ('image-grayscale', 'Grayscale & Black/White Photo Filter', 'Image Tools', 'Convert full-color photos into dramatic high-contrast monochrome black & white graphics.', 'Moon', '/tools/image-grayscale', 'image', true, false, false, 22, '{"title": "Black & White Photo Converter Online", "keywords": ["grayscale image", "black and white converter", "monochrome photo"], "description": "Convert color photos to monochrome black and white graphics."}'::jsonb, false),
  ('image-cropper', 'Square 1:1 Image Cropper & Avatar Maker', 'Image Tools', 'Crop images into clean 1:1 square aspect ratios for social media avatars and logos.', 'Crop', '/tools/image-cropper', 'image', true, false, false, 23, '{"title": "Square Image Cropper & Profile Avatar Maker", "keywords": ["square crop", "profile photo cropper", "avatar creator"], "description": "Crop graphics into perfect 1:1 square dimensions for avatars."}'::jsonb, false),
  ('svg-data-uri-gen', 'SVG Code to Data URI Converter', 'Image Tools', 'Encode inline raw SVG XML markup into clean URL-encoded CSS background-image URIs.', 'Code', '/tools/svg-data-uri-gen', 'textarea', true, false, false, 24, '{"title": "SVG to CSS Data URI Encoder", "keywords": ["svg to data uri", "encode svg", "svg css background"], "description": "Convert raw SVG code into CSS background-image data URI strings."}'::jsonb, false)
on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description, icon = excluded.icon, url = excluded.url, input_type = excluded.input_type, active = excluded.active, featured = excluded.featured, popular = excluded.popular, sort_order = excluded.sort_order, seo = excluded.seo, archived = excluded.archived;
