-- seed part 12 · tools (136) — rows 101-125 of 136
insert into public.tools (slug, name, category, description, icon, url, input_type, active, featured, popular, sort_order, seo, archived)
values
  ('investment-return-calculator', 'Investment Return Calculator', 'Finance Tools', 'Calculate future wealth accumulation from initial deposit and monthly contributions.', 'BarChart2', '/tools/investment-return-calculator', 'form', true, false, false, 100, '{"title": "Investment Return Calculator", "keywords": ["investment calculator", "investment returns", "future value"], "description": "Calculate future portfolio growth and interest returns."}'::jsonb, false),
  ('finance-roi-calculator', 'ROI Calculator (Finance)', 'Finance Tools', 'Calculate net ROI percentage and annualized returns on financial investments.', 'TrendingUp', '/tools/finance-roi-calculator', 'form', true, false, false, 101, '{"title": "Financial ROI Calculator", "keywords": ["roi calculator finance", "financial return", "annualized return"], "description": "Calculate Return on Investment (ROI) and annualized yield."}'::jsonb, false),
  ('savings-calculator', 'Savings Calculator', 'Finance Tools', 'Calculate monthly savings accumulation towards your financial goals.', 'PiggyBank', '/tools/savings-calculator', 'form', true, false, false, 102, '{"title": "Savings Goal Calculator", "keywords": ["savings calculator", "savings goal", "deposit growth"], "description": "Calculate savings growth over time with monthly deposits."}'::jsonb, false),
  ('percentage-calculator', 'Percentage Calculator', 'Finance Tools', 'Calculate percentage values, percentage increase/decrease, and proportions.', 'Percent', '/tools/percentage-calculator', 'form', true, false, false, 103, '{"title": "Percentage Calculator Online", "keywords": ["percentage calculator", "calculate percent", "percent difference"], "description": "Calculate percentage increase, decrease, and proportion values."}'::jsonb, false),
  ('currency-converter', 'Currency Converter', 'Finance Tools', 'Convert money amounts between USD, PKR, AED, EUR, GBP, CAD, and AUD.', 'RefreshCw', '/tools/currency-converter', 'form', true, true, false, 104, '{"title": "Currency Converter Tool", "keywords": ["currency converter", "usd to pkr", "usd to aed", "exchange rates"], "description": "Convert global currencies instantly in your browser."}'::jsonb, false),
  ('profit-loss-calculator', 'Profit/Loss Calculator', 'Finance Tools', 'Calculate net financial profit or loss percentage from trading or operations.', 'DollarSign', '/tools/profit-loss-calculator', 'form', true, false, false, 105, '{"title": "Profit & Loss Calculator", "keywords": ["profit loss calculator", "pnl calculator", "net profit"], "description": "Calculate financial net profit or loss amounts."}'::jsonb, false),
  ('gst-calculator', 'GST Calculator', 'Finance Tools', 'Add or remove Goods and Services Tax (GST) percentages (5%, 12%, 18%, 28%).', 'Calculator', '/tools/gst-calculator', 'form', true, false, false, 106, '{"title": "GST Calculator (Add / Remove GST)", "keywords": ["gst calculator", "add gst", "remove gst"], "description": "Calculate net price, GST amount, and gross total."}'::jsonb, false),
  ('vat-calculator', 'VAT Calculator', 'Finance Tools', 'Add or extract Value Added Tax (VAT) from prices.', 'Calculator', '/tools/vat-calculator', 'form', true, false, false, 107, '{"title": "VAT Calculator Tool", "keywords": ["vat calculator", "value added tax", "gross price"], "description": "Calculate VAT gross price or extract net price before tax."}'::jsonb, false),
  ('tip-calculator', 'Tip Calculator', 'Finance Tools', 'Calculate restaurant tip percentage and split bill total among dining guests.', 'Users', '/tools/tip-calculator', 'form', true, false, false, 108, '{"title": "Tip & Bill Splitter Calculator", "keywords": ["tip calculator", "split bill", "restaurant tip"], "description": "Calculate tip amount and split bill per person."}'::jsonb, false),
  ('debt-payoff-calculator', 'Debt Payoff Calculator', 'Finance Tools', 'Calculate exact months and interest cost required to pay off credit cards or debt.', 'CreditCard', '/tools/debt-payoff-calculator', 'form', true, false, false, 109, '{"title": "Debt Payoff Calculator", "keywords": ["debt payoff calculator", "payoff credit card", "debt timeline"], "description": "Calculate payoff timeline and total interest saved on debt."}'::jsonb, false),
  ('utm-builder', 'Google Analytics UTM Campaign Link Builder', 'Marketing Tools', 'Build tracking URLs with utm_source, utm_medium, and utm_campaign query parameters.', 'Link', '/tools/utm-builder', 'form', true, true, true, 110, '{"title": "UTM Campaign URL Builder Tool", "keywords": ["utm builder", "campaign URL builder", "google analytics utm"], "description": "Build Google Analytics tracking links with UTM parameters."}'::jsonb, false),
  ('hashtag-generator-mkt', 'Instagram & TikTok Hashtag Generator', 'Marketing Tools', 'Generate high-reach social hashtags for Instagram, TikTok, and LinkedIn posts.', 'Hash', '/tools/hashtag-generator-mkt', 'text', true, false, true, 111, '{"title": "Instagram & TikTok Hashtag Generator", "keywords": ["hashtag generator", "instagram hashtags", "tiktok hashtags"], "description": "Generate trending social hashtags for marketing campaigns."}'::jsonb, false),
  ('social-caption-hook-gen', 'Social Media Hook & Headline Generator', 'Marketing Tools', 'Generate 10 scroll-stopping headline hooks for Instagram reels, LinkedIn, and X.', 'Sparkles', '/tools/social-caption-hook-gen', 'text', true, false, false, 112, '{"title": "Social Media Headline & Hook Generator", "keywords": ["social media hooks", "caption generator", "viral headlines"], "description": "Generate viral headline hooks for social media content."}'::jsonb, false),
  ('email-subject-line-tester', 'Email Subject Line Score & Spam Tester', 'Marketing Tools', 'Evaluate email subject lines for open-rate potential, character length, and spam trigger words.', 'Mail', '/tools/email-subject-line-tester', 'text', true, false, false, 113, '{"title": "Email Subject Line Tester & Spam Checker", "keywords": ["email subject line tester", "spam trigger words", "email marketing"], "description": "Score email subject lines to boost open rates and inbox placement."}'::jsonb, false),
  ('cta-button-copy-gen', 'High-Converting CTA Button Copy Generator', 'Marketing Tools', 'Generate action-oriented Call to Action (CTA) button copy for landing pages.', 'MousePointer', '/tools/cta-button-copy-gen', 'text', true, false, false, 114, '{"title": "CTA Button Copy Generator for Landing Pages", "keywords": ["cta generator", "call to action copy", "landing page cta"], "description": "Generate converting Call-To-Action button copy."}'::jsonb, false),
  ('content-idea-generator', 'Blog & Content Topic Idea Generator', 'Marketing Tools', 'Generate 10 blog article headlines and video topic ideas based on your niche.', 'Lightbulb', '/tools/content-idea-generator', 'text', true, false, false, 115, '{"title": "Blog & Content Marketing Idea Generator", "keywords": ["content idea generator", "blog title ideas", "marketing topics"], "description": "Generate creative blog article titles and content marketing ideas."}'::jsonb, false),
  ('ad-copy-framework-gen', 'PAS & AIDA Copywriting Framework Builder', 'Marketing Tools', 'Structure ad copy using Problem-Agitate-Solve (PAS) and Attention-Interest-Desire-Action (AIDA).', 'Target', '/tools/ad-copy-framework-gen', 'form', true, false, false, 116, '{"title": "PAS & AIDA Ad Copy Framework Builder", "keywords": ["ad copy generator", "aida framework", "pas copywriting"], "description": "Generate marketing ad copy using proven PAS and AIDA frameworks."}'::jsonb, false),
  ('bio-generator-social', 'Social Media Bio & Profile Pitch Builder', 'Marketing Tools', 'Craft concise, high-impact bios for Instagram, X (Twitter), and LinkedIn profiles.', 'User', '/tools/bio-generator-social', 'form', true, false, false, 117, '{"title": "Instagram & LinkedIn Profile Bio Generator", "keywords": ["bio generator", "instagram bio", "linkedin headline generator"], "description": "Generate professional social media profile bios."}'::jsonb, false),
  ('tagline-slogan-generator', 'Brand Slogan & Tagline Generator', 'Marketing Tools', 'Generate memorable brand slogans and catchy marketing taglines.', 'Volume2', '/tools/tagline-slogan-generator', 'text', true, false, false, 118, '{"title": "Brand Slogan & Tagline Generator", "keywords": ["slogan generator", "brand tagline", "tagline ideas"], "description": "Generate catchy marketing slogans for startups."}'::jsonb, false),
  ('qr-code-utm-builder', 'Trackable QR Code & UTM Generator', 'Marketing Tools', 'Generate QR codes embedded with UTM tracking parameters for print collateral.', 'QrCode', '/tools/qr-code-utm-builder', 'form', true, false, false, 119, '{"title": "Trackable QR Code & UTM Generator", "keywords": ["trackable qr code", "utm qr code", "marketing qr code"], "description": "Generate QR codes with Google Analytics UTM parameters."}'::jsonb, false),
  ('target-audience-persona-gen', 'Customer Persona Profile Generator', 'Marketing Tools', 'Generate a structured buyer persona document detailing pain points, goals, and objection triggers.', 'Users', '/tools/target-audience-persona-gen', 'form', true, false, false, 120, '{"title": "Customer Buyer Persona Profile Generator", "keywords": ["persona generator", "buyer persona", "target audience profile"], "description": "Generate detailed target audience buyer personas."}'::jsonb, false),
  ('review-request-email-builder', 'Client Review & Testimonial Request Email Builder', 'Marketing Tools', 'Generate polite, high-converting review request emails to collect Trustpilot & Google reviews.', 'Star', '/tools/review-request-email-builder', 'form', true, false, false, 121, '{"title": "Client Review Request Email Template Builder", "keywords": ["review request email", "get google reviews", "testimonial request"], "description": "Generate review request emails to collect client testimonials."}'::jsonb, false),
  ('password-generator', 'Strong Random Password Generator', 'Security & Utility Tools', 'Generate cryptographically secure random passwords with customizable length and symbol rules.', 'Key', '/tools/password-generator', 'form', true, true, true, 122, '{"title": "Secure Random Password Generator Tool", "keywords": ["password generator", "random password", "secure password"], "description": "Generate secure random passwords up to 64 characters long."}'::jsonb, false),
  ('password-strength-checker', 'Password Security & Strength Tester', 'Security & Utility Tools', 'Test password entropy score, character complexity, and estimated crack time.', 'Shield', '/tools/password-strength-checker', 'text', true, false, true, 123, '{"title": "Password Security & Entropy Strength Tester", "keywords": ["password strength checker", "test password", "password security"], "description": "Check password security rating and crack time estimate."}'::jsonb, false),
  ('qr-code-generator', 'Instant QR Code Generator', 'Security & Utility Tools', 'Generate high-resolution QR codes for websites, Wi-Fi credentials, and contact cards.', 'QrCode', '/tools/qr-code-generator', 'text', true, true, true, 124, '{"title": "Free Online QR Code Generator — BRANIFY", "keywords": ["qr code generator", "make qr code", "free qr code"], "description": "Generate clean QR codes for website URLs and Wi-Fi networks."}'::jsonb, false)
on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description, icon = excluded.icon, url = excluded.url, input_type = excluded.input_type, active = excluded.active, featured = excluded.featured, popular = excluded.popular, sort_order = excluded.sort_order, seo = excluded.seo, archived = excluded.archived;
