-- seed part 11 · tools (136) — rows 76-100 of 136
insert into public.tools (slug, name, category, description, icon, url, input_type, active, featured, popular, sort_order, seo, archived)
values
  ('header-tag-structure-checker', 'Heading Tag (H1, H2, H3) Structure Inspector', 'SEO Tools', 'Paste HTML code to analyze heading hierarchy and ensure single H1 presence.', 'List', '/tools/header-tag-structure-checker', 'textarea', true, false, false, 75, '{"title": "H1 H2 H3 Heading Hierarchy Inspector", "keywords": ["h1 tag checker", "heading structure", "seo heading inspector"], "description": "Inspect web page heading hierarchy and spot missing H1 tags."}'::jsonb, false),
  ('alt-text-generator-guide', 'Image Alt Text Accessibility Helper', 'SEO Tools', 'Craft descriptive, keyword-rich alt text attributes for web accessibility and Google Image SEO.', 'Image', '/tools/alt-text-generator-guide', 'form', true, false, false, 76, '{"title": "Image Alt Text Generator for SEO & Accessibility", "keywords": ["alt text generator", "image alt tag", "seo image alt"], "description": "Generate accessible image alt text for SEO rankings."}'::jsonb, false),
  ('readability-score-checker', 'Flesch-Kincaid Readability Score Checker', 'SEO Tools', 'Calculate Flesch Reading Ease score and grade level for content clarity.', 'BookOpen', '/tools/readability-score-checker', 'textarea', true, false, false, 77, '{"title": "Flesch-Kincaid Readability Score Checker", "keywords": ["readability score", "flesch kincaid", "copy clarity test"], "description": "Score copy readability using Flesch-Kincaid formula."}'::jsonb, false),
  ('domain-extractor-tool', 'URL Domain & Hostname Extractor', 'SEO Tools', 'Extract root domains and clean URLs from bulk list of external links.', 'Globe', '/tools/domain-extractor-tool', 'textarea', true, false, false, 78, '{"title": "Extract Root Domains from List of URLs", "keywords": ["domain extractor", "extract domain from url", "clean url list"], "description": "Extract root domain names from a list of URLs."}'::jsonb, false),
  ('google-index-link-builder', 'Google Index Inspection Link Builder', 'SEO Tools', 'Generate quick Google site: search queries to verify if URLs are indexed.', 'Search', '/tools/google-index-link-builder', 'text', true, false, false, 79, '{"title": "Google Index Inspection Link Builder", "keywords": ["google index check", "site search link", "index status"], "description": "Generate Google site: query links to check if URLs are indexed."}'::jsonb, false),
  ('invoice-generator', 'Invoice Generator', 'Business Tools', 'Fill in client details, line items, tax rate, and generate a professional invoice text or document.', 'Receipt', '/tools/invoice-generator', 'form', true, true, true, 80, '{"title": "Free Invoice Generator — BRANIFY Tools", "keywords": ["invoice generator", "pdf invoice creator", "free invoice template"], "description": "Create professional business invoices online for free."}'::jsonb, false),
  ('business-name-generator', 'Business Name Generator', 'Business Tools', 'Generate creative startup and company name ideas based on target keyword or industry.', 'Sparkles', '/tools/business-name-generator', 'text', true, false, true, 81, '{"title": "Business Name Generator & Brand Ideas", "keywords": ["business name generator", "brand name ideas", "company names"], "description": "Generate creative business name ideas for startups."}'::jsonb, false),
  ('profit-margin-calculator', 'Profit Margin Calculator', 'Business Tools', 'Calculate gross profit margin percentage, net profit, and revenue markup.', 'DollarSign', '/tools/profit-margin-calculator', 'form', true, false, true, 82, '{"title": "Profit Margin Calculator", "keywords": ["profit margin calculator", "markup calculator", "gross margin"], "description": "Calculate gross profit margin percentage and selling price markup."}'::jsonb, false),
  ('markup-calculator', 'Markup Calculator', 'Business Tools', 'Calculate selling price based on cost price and desired percentage markup.', 'TrendingUp', '/tools/markup-calculator', 'form', true, false, false, 83, '{"title": "Markup Calculator Tool", "keywords": ["markup calculator", "price markup", "selling price"], "description": "Calculate target selling price and profit markup percentage."}'::jsonb, false),
  ('break-even-calculator', 'Break-Even Calculator', 'Business Tools', 'Calculate sales volume and revenue required to cover fixed and variable costs.', 'PieChart', '/tools/break-even-calculator', 'form', true, false, false, 84, '{"title": "Break-Even Point Calculator", "keywords": ["break even calculator", "break even point", "profitability"], "description": "Calculate units required to reach break-even profitability."}'::jsonb, false),
  ('roi-calculator', 'ROI Calculator', 'Business Tools', 'Calculate return on investment percentage and net profit for campaigns.', 'TrendingUp', '/tools/roi-calculator', 'form', true, true, false, 85, '{"title": "ROI Calculator Tool", "keywords": ["roi calculator", "return on investment", "business roi"], "description": "Calculate Return on Investment (ROI) percentage."}'::jsonb, false),
  ('business-growth-calculator', 'Business Growth Calculator', 'Business Tools', 'Project future business revenue and annual compound growth over time.', 'BarChart2', '/tools/business-growth-calculator', 'form', true, false, false, 86, '{"title": "Business Growth Calculator", "keywords": ["business growth calculator", "revenue growth", "cagr"], "description": "Project future business revenue growth and CAGR."}'::jsonb, false),
  ('commission-calculator', 'Commission Calculator', 'Business Tools', 'Calculate sales commission payouts based on sales volume and rate percentage.', 'DollarSign', '/tools/commission-calculator', 'form', true, false, false, 87, '{"title": "Sales Commission Calculator", "keywords": ["commission calculator", "sales commission", "payout"], "description": "Calculate sales commission payouts and rates."}'::jsonb, false),
  ('salary-calculator', 'Salary Calculator', 'Business Tools', 'Convert annual salary into monthly, bi-weekly, weekly, and hourly breakdowns.', 'Calculator', '/tools/salary-calculator', 'form', true, false, false, 88, '{"title": "Salary Calculator Tool", "keywords": ["salary calculator", "paycheck breakdown", "annual salary"], "description": "Break down annual salary into monthly and hourly pay rates."}'::jsonb, false),
  ('hourly-rate-calculator', 'Hourly Rate Calculator', 'Business Tools', 'Convert hourly freelancing or contractor rates into annual and monthly salary.', 'Clock', '/tools/hourly-rate-calculator', 'form', true, false, false, 89, '{"title": "Hourly Rate Calculator", "keywords": ["hourly rate calculator", "freelance rate", "annual salary"], "description": "Convert hourly rate to annual income and monthly pay."}'::jsonb, false),
  ('discount-calculator', 'Discount Calculator', 'Business Tools', 'Calculate final price after percentage or dollar discounts.', 'Tag', '/tools/discount-calculator', 'form', true, false, false, 90, '{"title": "Discount Calculator Tool", "keywords": ["discount calculator", "sale price", "savings"], "description": "Calculate discounted sale price and savings amount."}'::jsonb, false),
  ('tax-calculator', 'Tax Calculator', 'Business Tools', 'Calculate business sales tax and total price with tax included.', 'Calculator', '/tools/tax-calculator', 'form', true, false, false, 91, '{"title": "Sales Tax Calculator", "keywords": ["tax calculator", "sales tax", "business tax"], "description": "Calculate tax amount and gross total price."}'::jsonb, false),
  ('loan-payment-calculator', 'Loan Payment Calculator', 'Business Tools', 'Calculate monthly business loan repayments, interest rates, and loan terms.', 'CreditCard', '/tools/loan-payment-calculator', 'form', true, false, false, 92, '{"title": "Business Loan Payment Calculator", "keywords": ["loan payment calculator", "business loan", "loan repayment"], "description": "Calculate monthly loan repayments and total interest cost."}'::jsonb, false),
  ('pricing-calculator', 'Pricing Calculator', 'Business Tools', 'Determine optimal product or service pricing based on cost and target profit margin.', 'DollarSign', '/tools/pricing-calculator', 'form', true, false, false, 93, '{"title": "Product Pricing Calculator", "keywords": ["pricing calculator", "product pricing", "service rate"], "description": "Calculate optimal selling prices for products and services."}'::jsonb, false),
  ('quote-generator', 'Quote Generator', 'Business Tools', 'Generate formal client price quotes with itemized costs, tax, and terms.', 'FileText', '/tools/quote-generator', 'form', true, false, false, 94, '{"title": "Client Price Quote Generator", "keywords": ["quote generator", "price quote", "estimate builder"], "description": "Generate professional price quote documents for clients."}'::jsonb, false),
  ('compound-interest-calculator', 'Compound Interest Calculator', 'Finance Tools', 'Calculate interest compounding frequency over time and total investment balance.', 'TrendingUp', '/tools/compound-interest-calculator', 'form', true, true, true, 95, '{"title": "Compound Interest Calculator — BRANIFY", "keywords": ["compound interest calculator", "compound growth", "investment growth"], "description": "Calculate compound interest earnings and future investment growth."}'::jsonb, false),
  ('simple-interest-calculator', 'Simple Interest Calculator', 'Finance Tools', 'Calculate simple interest earned using Principal x Rate x Time formula.', 'DollarSign', '/tools/simple-interest-calculator', 'form', true, false, false, 96, '{"title": "Simple Interest Calculator", "keywords": ["simple interest calculator", "interest yield"], "description": "Calculate simple interest yield and total interest amount."}'::jsonb, false),
  ('emi-calculator', 'EMI Calculator', 'Finance Tools', 'Calculate Equated Monthly Installments (EMI) for personal, car, or business loans.', 'CreditCard', '/tools/emi-calculator', 'form', true, false, true, 97, '{"title": "EMI Calculator Tool", "keywords": ["emi calculator", "loan emi", "monthly installment"], "description": "Calculate Equated Monthly Installment (EMI) loan repayments."}'::jsonb, false),
  ('loan-calculator', 'Loan Calculator', 'Finance Tools', 'Calculate total loan cost, monthly principal + interest, and interest breakdown.', 'Calculator', '/tools/loan-calculator', 'form', true, false, false, 98, '{"title": "Personal & Business Loan Calculator", "keywords": ["loan calculator", "personal loan", "loan schedule"], "description": "Calculate monthly loan payments and overall interest paid."}'::jsonb, false),
  ('mortgage-calculator', 'Mortgage Calculator', 'Finance Tools', 'Calculate home mortgage monthly payments including principal and interest.', 'Home', '/tools/mortgage-calculator', 'form', true, false, false, 99, '{"title": "Home Mortgage Calculator", "keywords": ["mortgage calculator", "home loan", "mortgage payment"], "description": "Calculate monthly home mortgage payments and interest cost."}'::jsonb, false)
on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description, icon = excluded.icon, url = excluded.url, input_type = excluded.input_type, active = excluded.active, featured = excluded.featured, popular = excluded.popular, sort_order = excluded.sort_order, seo = excluded.seo, archived = excluded.archived;
