-- seed part 13 · tools (136) — rows 126-136 of 136
insert into public.tools (slug, name, category, description, icon, url, input_type, active, featured, popular, sort_order, seo, archived)
values
  ('random-number-generator', 'Random Number Generator (Range & Quantity)', 'Security & Utility Tools', 'Generate random numbers within custom minimum and maximum value ranges.', 'Hash', '/tools/random-number-generator', 'form', true, false, false, 125, '{"title": "Random Number Generator Tool", "keywords": ["random number generator", "number picker", "random integer"], "description": "Generate random numbers between specified minimum and maximum bounds."}'::jsonb, false),
  ('random-string-generator', 'Random Alphanumeric Secret Key Generator', 'Security & Utility Tools', 'Generate random alphanumeric string keys for API secrets and session tokens.', 'Lock', '/tools/random-string-generator', 'form', true, false, false, 126, '{"title": "Random Secret Key & Token Generator", "keywords": ["random string generator", "secret key generator", "api token generator"], "description": "Generate random alphanumeric key strings for API tokens."}'::jsonb, false),
  ('unix-timestamp-converter', 'Unix Epoch Timestamp Converter', 'Security & Utility Tools', 'Convert Unix epoch timestamps (seconds/ms) into human-readable UTC and local dates.', 'Clock', '/tools/unix-timestamp-converter', 'text', true, false, false, 127, '{"title": "Unix Epoch Timestamp Converter Online", "keywords": ["unix timestamp converter", "epoch converter", "unix time"], "description": "Convert Unix timestamps into readable UTC dates and local time."}'::jsonb, false),
  ('time-zone-converter-quick', 'Time Zone Converter (EST, UTC, GMT, PKT, GST)', 'Security & Utility Tools', 'Convert meeting times between UTC, EST, PST, GMT, PKT, and GST time zones.', 'Globe', '/tools/time-zone-converter-quick', 'form', true, false, false, 128, '{"title": "Global Time Zone Meeting Converter", "keywords": ["time zone converter", "utc to est", "world clock converter"], "description": "Convert times across UTC, EST, GMT, and PKT time zones."}'::jsonb, false),
  ('unit-converter-length-weight', 'Unit Measurement Converter (Length, Weight, Data)', 'Security & Utility Tools', 'Convert meters/feet, kg/lbs, and MB/GB units instantly.', 'Sliders', '/tools/unit-converter-length-weight', 'form', true, false, false, 129, '{"title": "Unit Measurement Converter Tool", "keywords": ["unit converter", "meters to feet", "kg to lbs"], "description": "Convert length, weight, and digital memory data units."}'::jsonb, false),
  ('ip-lookup-client-info', 'Client Device & Network Connection Info', 'Security & Utility Tools', 'Display your active browser viewport width, screen resolution, and online status.', 'Monitor', '/tools/ip-lookup-client-info', 'none', true, false, false, 130, '{"title": "My Viewport & Screen Info Inspector", "keywords": ["screen resolution inspector", "my device info", "browser specs"], "description": "Inspect your active device screen resolution and browser specs."}'::jsonb, false),
  ('htpasswd-generator', '.htpasswd Basic Auth Credential Generator', 'Security & Utility Tools', 'Generate Apache .htpasswd encrypted username and password lines.', 'Lock', '/tools/htpasswd-generator', 'form', true, false, false, 131, '{"title": ".htpasswd Apache Password Generator", "keywords": ["htpasswd generator", "apache password", "basic auth htpasswd"], "description": "Generate encrypted username:password entries for .htpasswd files."}'::jsonb, false),
  ('sub-net-cidr-calculator', 'IP Subnet CIDR Mask Calculator', 'Security & Utility Tools', 'Calculate subnet mask, total IP addresses, network address, and broadcast address.', 'Network', '/tools/sub-net-cidr-calculator', 'text', true, false, false, 132, '{"title": "IP Subnet CIDR Mask Calculator", "keywords": ["cidr calculator", "subnet calculator", "ip address range"], "description": "Calculate IP subnet ranges, network addresses, and CIDR masks."}'::jsonb, false),
  ('screen-resolution-tester', 'Screen Resolution & Viewport Aspect Inspector', 'Security & Utility Tools', 'Check your current monitor resolution, CSS device pixel ratio, and orientation.', 'Smartphone', '/tools/screen-resolution-tester', 'none', true, false, false, 133, '{"title": "Screen Resolution & Device Pixel Ratio Inspector", "keywords": ["screen resolution test", "viewport size", "pixel ratio"], "description": "Test active screen width, height, and device pixel ratio."}'::jsonb, false),
  ('my-browser-storage-cleared', 'Browser Local Storage Usage Inspector', 'Security & Utility Tools', 'Check active browser localStorage items, key sizes, and available storage quota.', 'Database', '/tools/my-browser-storage-cleared', 'none', true, false, false, 134, '{"title": "Browser Local Storage Quota Inspector", "keywords": ["localstorage inspector", "browser storage usage"], "description": "Inspect localStorage items and browser memory usage."}'::jsonb, false),
  ('csp-header-generator', 'Content Security Policy (CSP) Header Builder', 'Security & Utility Tools', 'Build valid HTTP Content-Security-Policy headers to prevent XSS attacks.', 'ShieldCheck', '/tools/csp-header-generator', 'form', true, false, false, 135, '{"title": "Content Security Policy (CSP) Header Generator", "keywords": ["csp header generator", "content security policy", "xss protection header"], "description": "Generate HTTP Content-Security-Policy headers for web security."}'::jsonb, false)
on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description, icon = excluded.icon, url = excluded.url, input_type = excluded.input_type, active = excluded.active, featured = excluded.featured, popular = excluded.popular, sort_order = excluded.sort_order, seo = excluded.seo, archived = excluded.archived;
