-- seed part 09 · tools (136) — rows 26-50 of 136
insert into public.tools (slug, name, category, description, icon, url, input_type, active, featured, popular, sort_order, seo, archived)
values
  ('image-flipper-rotator', 'Image Rotate & Flip Tool', 'Image Tools', 'Rotate photos 90°, 180°, or 270° and mirror flip horizontally or vertically.', 'RotateCw', '/tools/image-flipper-rotator', 'image', true, false, false, 25, '{"title": "Rotate & Flip Image Online Tool", "keywords": ["rotate image", "flip photo", "mirror image online"], "description": "Rotate images 90 degrees or flip horizontally and vertically."}'::jsonb, false),
  ('social-image-dimensions', 'Social Media Image Dimension Cheat Sheet', 'Image Tools', 'Quick reference guide for Instagram, LinkedIn, YouTube, Facebook, and Twitter banner sizes.', 'Layout', '/tools/social-image-dimensions', 'none', true, false, false, 26, '{"title": "Social Media Image Dimensions Guide 2026", "keywords": ["social media sizes", "instagram photo dimensions", "linkedin banner size"], "description": "Check exact image size requirements for Instagram, LinkedIn, YouTube, and Facebook."}'::jsonb, false),
  ('word-counter', 'Word Counter', 'Text & Content Tools', 'Live counting of words, characters, sentences, paragraphs, and estimated reading time.', 'FileText', '/tools/word-counter', 'textarea', true, true, true, 27, '{"title": "Free Word Counter — BRANIFY Tools", "keywords": ["word counter", "count words", "word count tool"], "description": "Count words, characters, sentences, paragraphs, and reading time instantly."}'::jsonb, false),
  ('character-counter', 'Character Counter', 'Text & Content Tools', 'Count exact characters with and without spaces, plus letter and symbol breakdowns.', 'Hash', '/tools/character-counter', 'textarea', true, false, true, 28, '{"title": "Character Counter Online", "keywords": ["character counter", "count characters", "letter counter"], "description": "Count total characters with and without spaces for posts and ads."}'::jsonb, false),
  ('sentence-counter', 'Sentence Counter', 'Text & Content Tools', 'Count total sentences and average sentence length in words.', 'ListFilter', '/tools/sentence-counter', 'textarea', true, false, false, 29, '{"title": "Sentence Counter Tool", "keywords": ["sentence counter", "count sentences"], "description": "Analyze total sentences and readability metrics."}'::jsonb, false),
  ('paragraph-counter', 'Paragraph Counter', 'Text & Content Tools', 'Count total paragraphs and content block structure.', 'AlignLeft', '/tools/paragraph-counter', 'textarea', true, false, false, 30, '{"title": "Paragraph Counter Tool", "keywords": ["paragraph counter", "count paragraphs"], "description": "Count paragraphs and block sections in copy."}'::jsonb, false),
  ('reading-time-calculator', 'Reading Time Calculator', 'Text & Content Tools', 'Calculate estimated silent reading time and speech presentation duration.', 'Clock', '/tools/reading-time-calculator', 'textarea', true, false, false, 31, '{"title": "Reading & Speaking Time Calculator", "keywords": ["reading time calculator", "speech length calculator"], "description": "Calculate estimated reading time and speech duration."}'::jsonb, false),
  ('case-converter', 'Case Converter', 'Text & Content Tools', 'Convert text between UPPERCASE, lowercase, Title Case, camelCase, kebab-case, and snake_case.', 'Type', '/tools/case-converter', 'textarea', true, false, true, 32, '{"title": "Online Case Converter Tool", "keywords": ["case converter", "uppercase", "lowercase", "title case"], "description": "Transform copy into UPPERCASE, lowercase, Title Case, camelCase, kebab-case."}'::jsonb, false),
  ('uppercase-converter', 'Uppercase Converter', 'Text & Content Tools', 'Convert all text letters into bold ALL CAPS UPPERCASE.', 'Type', '/tools/uppercase-converter', 'textarea', true, false, false, 33, '{"title": "Uppercase Converter Tool", "keywords": ["uppercase converter", "all caps"], "description": "Convert copy into ALL CAPS UPPERCASE."}'::jsonb, false),
  ('lowercase-converter', 'Lowercase Converter', 'Text & Content Tools', 'Convert all text letters into clean lowercase characters.', 'Type', '/tools/lowercase-converter', 'textarea', true, false, false, 34, '{"title": "Lowercase Converter Tool", "keywords": ["lowercase converter", "small letters"], "description": "Convert copy into lowercase text."}'::jsonb, false),
  ('title-case-converter', 'Title Case Converter', 'Text & Content Tools', 'Capitalize the first letter of each word for headlines and titles.', 'Type', '/tools/title-case-converter', 'textarea', true, false, false, 35, '{"title": "Title Case Converter Tool", "keywords": ["title case converter", "capitalize title"], "description": "Capitalize title words for articles and headlines."}'::jsonb, false),
  ('duplicate-line-remover', 'Remove Duplicate Lines', 'Text & Content Tools', 'Filter out duplicate lines from list data while preserving original sequence.', 'ListOrdered', '/tools/duplicate-line-remover', 'textarea', true, false, false, 36, '{"title": "Remove Duplicate Lines Online Tool", "keywords": ["remove duplicate lines", "deduplicate list"], "description": "Remove duplicate lines from lists and data."}'::jsonb, false),
  ('remove-extra-spaces', 'Remove Extra Spaces', 'Text & Content Tools', 'Clean text by stripping multiple spaces, double line breaks, and trailing tabs.', 'Sparkles', '/tools/remove-extra-spaces', 'textarea', true, false, false, 37, '{"title": "Remove Double Spaces & Blank Lines", "keywords": ["remove extra spaces", "clean text"], "description": "Clean text copy by removing extra spaces."}'::jsonb, false),
  ('text-sorter', 'Text Sorter', 'Text & Content Tools', 'Sort lists alphabetically (A-Z or Z-A) or by line length.', 'ArrowUpDown', '/tools/text-sorter', 'textarea', true, false, false, 38, '{"title": "Alphabetical Text & List Sorter", "keywords": ["text sorter", "alphabetical sorter"], "description": "Sort lines alphabetically or by length."}'::jsonb, false),
  ('text-reverser', 'Text Reverser', 'Text & Content Tools', 'Reverse text characters, word order, or line sequences.', 'RotateCcw', '/tools/text-reverser', 'textarea', true, false, false, 39, '{"title": "Text Reverser Tool", "keywords": ["text reverser", "flip text"], "description": "Reverse characters or word orders."}'::jsonb, false),
  ('text-cleaner', 'Text Cleaner', 'Text & Content Tools', 'Sanitize text, strip HTML tags, fix broken line breaks, and clean unprintable characters.', 'Sparkles', '/tools/text-cleaner', 'textarea', true, false, false, 40, '{"title": "Text Cleaner & Sanitizer Tool", "keywords": ["text cleaner", "sanitize text"], "description": "Clean text formatting and strip invalid symbols."}'::jsonb, false),
  ('find-and-replace', 'Find & Replace', 'Text & Content Tools', 'Search and replace words or phrases inside large copy blocks.', 'Search', '/tools/find-and-replace', 'form', true, false, false, 41, '{"title": "Find & Replace Text Tool", "keywords": ["find and replace", "replace text"], "description": "Find and replace target words across long documents."}'::jsonb, false),
  ('lorem-ipsum-generator', 'Lorem Ipsum Generator', 'Text & Content Tools', 'Generate paragraphs or words of standard dummy placeholder text.', 'AlignLeft', '/tools/lorem-ipsum-generator', 'form', true, false, false, 42, '{"title": "Lorem Ipsum Filler Text Generator", "keywords": ["lorem ipsum generator", "filler text"], "description": "Generate custom lorem ipsum filler text for website design."}'::jsonb, false),
  ('random-text-generator', 'Random Text Generator', 'Text & Content Tools', 'Generate randomized mock sentences, paragraphs, or word sequences.', 'Shuffle', '/tools/random-text-generator', 'form', true, false, false, 43, '{"title": "Random Text Generator Tool", "keywords": ["random text generator", "mock copy"], "description": "Generate random sentences for layout testing."}'::jsonb, false),
  ('hashtag-generator', 'Hashtag Generator', 'Text & Content Tools', 'Generate targeted social media hashtags based on topic keywords.', 'Hash', '/tools/hashtag-generator', 'text', true, false, false, 44, '{"title": "Hashtag Generator Tool", "keywords": ["hashtag generator", "social hashtags"], "description": "Generate popular hashtags for social posts."}'::jsonb, false),
  ('keyword-density-checker', 'Keyword Density Checker', 'Text & Content Tools', 'Analyze word frequencies and 1-word, 2-word, and 3-word phrase density percentages.', 'BarChart2', '/tools/keyword-density-checker', 'textarea', true, false, false, 45, '{"title": "Keyword Density Checker Tool", "keywords": ["keyword density checker", "word frequency"], "description": "Analyze keyword frequency and density percentages."}'::jsonb, false),
  ('text-summarizer', 'Text Summarizer', 'Text & Content Tools', 'Extract key bullet sentences and core takeaways from long articles.', 'FileText', '/tools/text-summarizer', 'textarea', true, false, false, 46, '{"title": "Text Summarizer Tool", "keywords": ["text summarizer", "summarize text"], "description": "Summarize long documents into concise key bullet points."}'::jsonb, false),
  ('json-formatter', 'JSON Formatter', 'Text & Content Tools', 'Beautify, validate, and format raw JSON code with syntax checks.', 'Code', '/tools/json-formatter', 'textarea', true, false, false, 47, '{"title": "JSON Formatter & Validator", "keywords": ["json formatter", "beautify json"], "description": "Format and beautify JSON objects with syntax validation."}'::jsonb, false),
  ('markdown-formatter', 'Markdown Formatter', 'Text & Content Tools', 'Format Markdown text and generate live rendered HTML previews.', 'FileCode', '/tools/markdown-formatter', 'textarea', true, false, false, 48, '{"title": "Markdown Formatter & Previewer", "keywords": ["markdown formatter", "markdown preview"], "description": "Format Markdown code and preview styled output."}'::jsonb, false),
  ('slug-generator', 'Slug Generator', 'Text & Content Tools', 'Convert headlines and titles into clean lowercased URL web slugs.', 'Link', '/tools/slug-generator', 'text', true, false, false, 49, '{"title": "URL Slug Generator Tool", "keywords": ["slug generator", "url slug"], "description": "Generate clean URL web slugs from article titles."}'::jsonb, false)
on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description, icon = excluded.icon, url = excluded.url, input_type = excluded.input_type, active = excluded.active, featured = excluded.featured, popular = excluded.popular, sort_order = excluded.sort_order, seo = excluded.seo, archived = excluded.archived;
