-- seed part 10 · tools (136) — rows 51-75 of 136
insert into public.tools (slug, name, category, description, icon, url, input_type, active, featured, popular, sort_order, seo, archived)
values
  ('json-formatter-dev', 'JSON Formatter & Validator', 'Developer Tools', 'Pretty-print, validate, and structure raw JSON strings with 2-space indentation.', 'Code', '/tools/json-formatter-dev', 'textarea', true, true, true, 50, '{"title": "JSON Formatter & Validator Online", "keywords": ["json formatter", "json validator", "beautify json"], "description": "Beautify and validate JSON objects with error highlighting."}'::jsonb, false),
  ('json-minifier', 'JSON Minifier & Compact Tool', 'Developer Tools', 'Strip whitespaces and line breaks from JSON payloads to reduce bandwidth.', 'Minimize2', '/tools/json-minifier', 'textarea', true, false, false, 51, '{"title": "JSON Minifier & Compression Tool", "keywords": ["json minifier", "compress json", "single line json"], "description": "Minify JSON objects for faster API payloads."}'::jsonb, false),
  ('base64-encoder-decoder', 'Base64 Encoder & Decoder', 'Developer Tools', 'Convert plain text to Base64 strings or decode Base64 back into clear text.', 'Key', '/tools/base64-encoder-decoder', 'textarea', true, false, true, 52, '{"title": "Base64 Encoder & Decoder Online", "keywords": ["base64 encoder", "base64 decoder", "atob btoa online"], "description": "Encode and decode strings using standard Base64 encoding."}'::jsonb, false),
  ('url-encoder-decoder', 'URL Percent Encoder & Decoder', 'Developer Tools', 'Encode query string parameters (%20 format) or decode URL encoded links.', 'Link', '/tools/url-encoder-decoder', 'textarea', true, false, false, 53, '{"title": "URL Encoder & Decoder Tool", "keywords": ["url encoder", "url decoder", "percent encode url"], "description": "Percent-encode URL parameters for safe web requests."}'::jsonb, false),
  ('uuid-generator', 'UUID v4 GUID Generator', 'Developer Tools', 'Generate cryptographically secure v4 UUIDs / GUIDs in bulk.', 'Cpu', '/tools/uuid-generator', 'form', true, true, false, 54, '{"title": "Bulk UUID v4 Generator Online", "keywords": ["uuid generator", "guid generator", "random uuid"], "description": "Generate random, secure UUID v4 / GUID strings."}'::jsonb, false),
  ('html-entity-encoder', 'HTML Entity Encoder & Escaper', 'Developer Tools', 'Escape special HTML symbols (&, <, >, ", '') into safe HTML entity codes.', 'Code', '/tools/html-entity-encoder', 'textarea', true, false, false, 55, '{"title": "HTML Entity Encoder & Decoder", "keywords": ["html encoder", "escape html", "html entities"], "description": "Escape special characters into HTML entity codes."}'::jsonb, false),
  ('css-minifier', 'CSS Code Minifier', 'Developer Tools', 'Minify CSS code by stripping comments, extra spaces, and redundant semicolons.', 'FileCode', '/tools/css-minifier', 'textarea', true, false, false, 56, '{"title": "CSS Minifier Online Tool", "keywords": ["css minifier", "compress css", "clean css"], "description": "Compress CSS stylesheets for faster web page speed."}'::jsonb, false),
  ('js-minifier-helper', 'JavaScript Syntax & Format Cleaner', 'Developer Tools', 'Clean JavaScript code formatting, strip inline comments, and collapse line breaks.', 'FileCode', '/tools/js-minifier-helper', 'textarea', true, false, false, 57, '{"title": "JavaScript Code Cleaner & Formatter", "keywords": ["js cleaner", "minify javascript", "clean js code"], "description": "Clean JavaScript code and strip single line comments."}'::jsonb, false),
  ('hash-generator-md5-sha256', 'SHA-256 Hash Generator', 'Developer Tools', 'Compute SHA-256 cryptographic message digest hashes for data verification.', 'Lock', '/tools/hash-generator-md5-sha256', 'textarea', true, false, false, 58, '{"title": "SHA-256 Hash Generator Online", "keywords": ["sha256 generator", "hash generator", "sha256 online"], "description": "Generate SHA-256 cryptographic hashes instantly."}'::jsonb, false),
  ('jwt-decoder-inspector', 'JWT Token Decoder & Inspector', 'Developer Tools', 'Decode JSON Web Token (JWT) headers and payloads without sending secret keys.', 'ShieldCheck', '/tools/jwt-decoder-inspector', 'textarea', true, false, false, 59, '{"title": "JWT Decoder & Inspector Online", "keywords": ["jwt decoder", "decode jwt", "inspect jwt token"], "description": "Decode JSON Web Tokens (JWT) to inspect header and payload data."}'::jsonb, false),
  ('sql-query-formatter', 'SQL Query Formatter & Beautifier', 'Developer Tools', 'Beautify SQL SELECT, INSERT, UPDATE, and JOIN queries into formatted readable lines.', 'Database', '/tools/sql-query-formatter', 'textarea', true, false, false, 60, '{"title": "SQL Query Formatter Online", "keywords": ["sql formatter", "beautify sql", "sql query cleaner"], "description": "Format and beautify complex SQL queries for database analysis."}'::jsonb, false),
  ('curl-to-fetch-converter', 'cURL to JavaScript fetch() Converter', 'Developer Tools', 'Convert cURL terminal commands into modern JavaScript fetch API code snippets.', 'Terminal', '/tools/curl-to-fetch-converter', 'textarea', true, false, false, 61, '{"title": "Convert cURL to JavaScript fetch() Code", "keywords": ["curl to fetch", "convert curl to js", "fetch API request"], "description": "Translate cURL terminal commands into JS fetch() request syntax."}'::jsonb, false),
  ('color-hex-rgb-converter', 'HEX to RGB / RGBA Color Converter', 'Developer Tools', 'Convert HEX color codes (#F27D26) to RGB values and CSS Tailwind class names.', 'Palette', '/tools/color-hex-rgb-converter', 'text', true, false, false, 62, '{"title": "HEX to RGB & RGBA Color Converter", "keywords": ["hex to rgb", "color converter", "hex code to rgb"], "description": "Convert HEX color codes into RGB values for CSS styling."}'::jsonb, false),
  ('cron-expression-explainer', 'Cron Expression Schedule Translator', 'Developer Tools', 'Decode 5-part cron syntax (e.g. 0 0 * * *) into plain English schedule descriptions.', 'Clock', '/tools/cron-expression-explainer', 'text', true, false, false, 63, '{"title": "Cron Expression Translator & Generator", "keywords": ["cron expression", "cron translator", "cron schedule helper"], "description": "Translate cron schedule expressions into clear human readability."}'::jsonb, false),
  ('user-agent-parser', 'Browser User-Agent Parser', 'Developer Tools', 'Inspect browser engine, operating system, device type, and client features.', 'Laptop', '/tools/user-agent-parser', 'none', true, false, false, 64, '{"title": "Browser User-Agent & Device Inspector", "keywords": ["user agent parser", "my user agent", "browser inspector"], "description": "Analyze your browser user-agent string and operating system details."}'::jsonb, false),
  ('meta-title-description-gen', 'SEO Meta Title & Description Generator', 'SEO Tools', 'Generate Google snippet meta title and description tag markup with character count safety checks.', 'Globe', '/tools/meta-title-description-gen', 'form', true, true, true, 65, '{"title": "SEO Meta Title & Description Tag Generator", "keywords": ["meta tag generator", "seo title tag", "meta description generator"], "description": "Generate optimized meta title and description tag markup."}'::jsonb, false),
  ('serp-snippet-preview', 'Google SERP Search Snippet Preview', 'SEO Tools', 'Simulate how your webpage title, URL, and meta description will appear on Google Desktop & Mobile search results.', 'Search', '/tools/serp-snippet-preview', 'form', true, false, true, 66, '{"title": "Google SERP Snippet Preview Tool", "keywords": ["serp preview", "google snippet simulator", "seo search preview"], "description": "Preview how web pages look on Google search results."}'::jsonb, false),
  ('keyword-density-checker-seo', 'SEO Keyword Density Analyzer', 'SEO Tools', 'Analyze word frequency percentages to spot over-optimization and keyword stuffing risks.', 'BarChart2', '/tools/keyword-density-checker-seo', 'textarea', true, false, false, 67, '{"title": "SEO Keyword Density Analyzer Tool", "keywords": ["keyword density", "word frequency analyzer", "seo copy checker"], "description": "Check word frequency and density percentage for SEO optimization."}'::jsonb, false),
  ('robots-txt-generator', 'Robots.txt Generator', 'SEO Tools', 'Generate valid robots.txt files to guide Googlebot crawler indexing and sitemap links.', 'Bot', '/tools/robots-txt-generator', 'form', true, true, false, 68, '{"title": "Robots.txt File Generator Online", "keywords": ["robots txt generator", "make robots txt", "googlebot rules"], "description": "Generate custom robots.txt files for search engine crawlers."}'::jsonb, false),
  ('sitemap-xml-generator-helper', 'Sitemap.xml Structure Builder', 'SEO Tools', 'Generate valid XML sitemap code entries with changefreq and priority attributes.', 'Map', '/tools/sitemap-xml-generator-helper', 'form', true, false, false, 69, '{"title": "XML Sitemap Code Builder Tool", "keywords": ["sitemap generator", "xml sitemap builder", "google sitemap"], "description": "Generate XML sitemap markup for search engines."}'::jsonb, false),
  ('schema-markup-organization', 'JSON-LD Organization Schema Generator', 'SEO Tools', 'Generate Schema.org Organization structured data code for Google Rich Results.', 'Code', '/tools/schema-markup-organization', 'form', true, false, false, 70, '{"title": "JSON-LD Organization Schema Generator", "keywords": ["organization schema", "json-ld schema", "schema org generator"], "description": "Generate Schema.org Organization structured data markup."}'::jsonb, false),
  ('schema-faq-generator', 'JSON-LD FAQ Schema Markup Generator', 'SEO Tools', 'Build FAQ Page structured data markup to qualify for Google FAQ rich snippet accordions.', 'HelpCircle', '/tools/schema-faq-generator', 'form', true, false, false, 71, '{"title": "FAQ Schema Markup Generator Online", "keywords": ["faq schema generator", "json ld faq", "rich snippet faq"], "description": "Generate FAQ Page JSON-LD schema markup for rich snippets."}'::jsonb, false),
  ('open-graph-tag-gen', 'Open Graph (OG) Meta Tag Generator', 'SEO Tools', 'Generate og:title, og:description, og:image, and Twitter Card tags for social media sharing.', 'Share2', '/tools/open-graph-tag-gen', 'form', true, false, false, 72, '{"title": "Open Graph Meta Tag Generator for Social Media", "keywords": ["open graph generator", "og image tags", "twitter card tags"], "description": "Generate og:image, og:title, and Twitter Card tags for link previews."}'::jsonb, false),
  ('redirect-htaccess-gen', '301 Redirect .htaccess Code Generator', 'SEO Tools', 'Generate Apache .htaccess 301 Permanent Redirect rules for domain migrations.', 'ArrowRightLeft', '/tools/redirect-htaccess-gen', 'form', true, false, false, 73, '{"title": "301 Redirect .htaccess Generator", "keywords": ["301 redirect generator", "htaccess redirect", "permanent redirect"], "description": "Generate 301 redirect rules for .htaccess files."}'::jsonb, false),
  ('canonical-tag-gen', 'Canonical Tag Generator', 'SEO Tools', 'Generate rel="canonical" HTML link tags to prevent duplicate content indexing issues.', 'Link2', '/tools/canonical-tag-gen', 'text', true, false, false, 74, '{"title": "Canonical URL Tag Generator", "keywords": ["canonical tag generator", "rel canonical", "duplicate content fix"], "description": "Generate HTML canonical link tags to avoid duplicate content penalties."}'::jsonb, false)
on conflict (slug) do update set name = excluded.name, category = excluded.category, description = excluded.description, icon = excluded.icon, url = excluded.url, input_type = excluded.input_type, active = excluded.active, featured = excluded.featured, popular = excluded.popular, sort_order = excluded.sort_order, seo = excluded.seo, archived = excluded.archived;
